    USE ENGLISH_CENTER;

    INSERT INTO CLASSROOM VALUES('ROOM01',20);
    INSERT INTO CLASSROOM VALUES('ROOM02',25);
    INSERT INTO CLASSROOM VALUES('ROOM03',30);
    INSERT INTO CLASSROOM VALUES('ROOM04',40);
    INSERT INTO CLASSROOM VALUES('ROOM05',15);
    INSERT INTO CLASSROOM VALUES('ROOM06',30);
    INSERT INTO CLASSROOM VALUES('ROOM07',25);
    INSERT INTO CLASSROOM VALUES('ROOM08',40);
    INSERT INTO CLASSROOM VALUES('ROOM09',35);
    INSERT INTO CLASSROOM VALUES('ROOM10',30);