USE ENGLISH_CENTER;

INSERT INTO CLASSROOM VALUES('R01',20);
INSERT INTO CLASSROOM VALUES('R02',25);
INSERT INTO CLASSROOM VALUES('R03',30);
INSERT INTO CLASSROOM VALUES('R04',40);
INSERT INTO CLASSROOM VALUES('R05',15);
INSERT INTO CLASSROOM VALUES('R06',30);
INSERT INTO CLASSROOM VALUES('R07',25);
INSERT INTO CLASSROOM VALUES('R08',40);
INSERT INTO CLASSROOM VALUES('R09',35);
INSERT INTO CLASSROOM VALUES('R10',30);