use english_center;

call createClass('TOEIC01','2023-04-01','2023-07-10','ROOM01',36);
call GenSession('TOEIC01','2023-04-01','2023-07-10','Monday','1','ROOM01',0,3);
call GenSession('TOEIC01','2023-04-01','2023-07-10','Tuesday','1','ROOM01',1,3);
call GenSession('TOEIC01','2023-04-01','2023-07-10','Wednesday','1','ROOM01',2,3);
insert into TEACH values('TEACHER01','TOEIC01');
insert into TEACH values('TEACHER02','TOEIC01');
insert into TEACH values('TEACHER04','TOEIC01');
call AssignSessionForTeacher(1,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(1,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(2,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(2,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(3,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(3,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(4,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(4,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(5,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(5,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(6,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(6,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(7,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(7,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(8,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(8,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(9,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(9,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(10,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(10,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(11,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(11,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(12,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(12,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(13,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(13,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(14,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(14,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(15,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(15,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(16,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(16,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(17,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(17,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(18,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(18,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(19,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(19,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(20,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(20,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(21,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(21,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(22,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(22,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(23,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(23,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(24,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(24,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(25,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(25,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(26,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(26,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(27,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(27,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(28,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(28,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(29,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(29,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(30,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(30,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(31,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(31,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(32,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(32,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(33,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(33,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(34,'TOEIC01','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(34,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(35,'TOEIC01','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(35,'TOEIC01','SUPERVISOR02',null);
call AssignSessionForTeacher(36,'TOEIC01','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(36,'TOEIC01','SUPERVISOR02',null);
call createClass('TOEIC02','2023-03-01','2023-06-09','ROOM03',36);
call GenSession('TOEIC02','2023-03-01','2023-06-09','Monday','1','ROOM03',0,3);
call GenSession('TOEIC02','2023-03-01','2023-06-09','Thursday','3','ROOM03',1,3);
call GenSession('TOEIC02','2023-03-01','2023-06-09','Saturday','5','ROOM03',2,3);
insert into TEACH values('TEACHER01','TOEIC02');
insert into TEACH values('TEACHER02','TOEIC02');
insert into TEACH values('TEACHER04','TOEIC02');
insert into TEACH values('TEACHER05','TOEIC02');
-- insert into TEACH values('TEACHER04','TOEIC02');
insert into TEACH values('TEACHER07','TOEIC02');
call AssignSessionForTeacher(1,'TOEIC02','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(1,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(2,'TOEIC02','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(2,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(3,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(3,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(4,'TOEIC02','TEACHER05');
insert into SUPERVISOR_RESPONSIBLE values(4,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(5,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(5,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(6,'TOEIC02','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(6,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(7,'TOEIC02','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(7,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(8,'TOEIC02','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(8,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(9,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(9,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(10,'TOEIC02','TEACHER05');
insert into SUPERVISOR_RESPONSIBLE values(10,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(11,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(11,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(12,'TOEIC02','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(12,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(13,'TOEIC02','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(13,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(14,'TOEIC02','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(14,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(15,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(15,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(16,'TOEIC02','TEACHER05');
insert into SUPERVISOR_RESPONSIBLE values(16,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(17,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(17,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(18,'TOEIC02','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(18,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(19,'TOEIC02','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(19,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(20,'TOEIC02','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(20,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(21,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(21,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(22,'TOEIC02','TEACHER05');
insert into SUPERVISOR_RESPONSIBLE values(22,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(23,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(23,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(24,'TOEIC02','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(24,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(25,'TOEIC02','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(25,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(26,'TOEIC02','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(26,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(27,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(27,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(28,'TOEIC02','TEACHER05');
insert into SUPERVISOR_RESPONSIBLE values(28,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(29,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(29,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(30,'TOEIC02','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(30,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(31,'TOEIC02','TEACHER01');
insert into SUPERVISOR_RESPONSIBLE values(31,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(32,'TOEIC02','TEACHER02');
insert into SUPERVISOR_RESPONSIBLE values(32,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(33,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(33,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(34,'TOEIC02','TEACHER05');
insert into SUPERVISOR_RESPONSIBLE values(34,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(35,'TOEIC02','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(35,'TOEIC02','SUPERVISOR04',null);
call AssignSessionForTeacher(36,'TOEIC02','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(36,'TOEIC02','SUPERVISOR04',null);
call createClass('TOEIC03','2023-03-01','2023-06-09','ROOM03',36);
call GenSession('TOEIC03','2023-03-01','2023-06-09','Tuesday','5','ROOM03',0,3);
call GenSession('TOEIC03','2023-03-01','2023-06-09','Thursday','4','ROOM03',1,3);
call GenSession('TOEIC03','2023-03-01','2023-06-09','Friday','1','ROOM03',2,3);
insert into TEACH values('TEACHER03','TOEIC03');
insert into TEACH values('TEACHER07','TOEIC03');
call AssignSessionForTeacher(1,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(1,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(2,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(2,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(3,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(3,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(4,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(4,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(5,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(5,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(6,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(6,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(7,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(7,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(8,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(8,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(9,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(9,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(10,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(10,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(11,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(11,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(12,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(12,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(13,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(13,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(14,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(14,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(15,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(15,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(16,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(16,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(17,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(17,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(18,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(18,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(19,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(19,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(20,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(20,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(21,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(21,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(22,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(22,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(23,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(23,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(24,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(24,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(25,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(25,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(26,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(26,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(27,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(27,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(28,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(28,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(29,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(29,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(30,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(30,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(31,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(31,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(32,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(32,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(33,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(33,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(34,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(34,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(35,'TOEIC03','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(35,'TOEIC03','SUPERVISOR03',null);
call AssignSessionForTeacher(36,'TOEIC03','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(36,'TOEIC03','SUPERVISOR03',null);
call createClass('TOEIC04','2023-04-01','2023-07-10','ROOM04',36);
call GenSession('TOEIC04','2023-04-01','2023-07-10','Tuesday','6','ROOM04',0,3);
call GenSession('TOEIC04','2023-04-01','2023-07-10','Wednesday','1','ROOM04',1,3);
call GenSession('TOEIC04','2023-04-01','2023-07-10','Saturday','4','ROOM04',2,3);
insert into TEACH values('TEACHER03','TOEIC04');
insert into TEACH values('TEACHER07','TOEIC04');
insert into TEACH values('TEACHER04','TOEIC04');
-- insert into TEACH values('TEACHER07','TOEIC04');
call AssignSessionForTeacher(1,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(1,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(2,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(2,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(3,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(3,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(4,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(4,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(5,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(5,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(6,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(6,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(7,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(7,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(8,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(8,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(9,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(9,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(10,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(10,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(11,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(11,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(12,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(12,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(13,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(13,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(14,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(14,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(15,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(15,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(16,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(16,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(17,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(17,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(18,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(18,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(19,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(19,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(20,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(20,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(21,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(21,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(22,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(22,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(23,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(23,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(24,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(24,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(25,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(25,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(26,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(26,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(27,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(27,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(28,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(28,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(29,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(29,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(30,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(30,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(31,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(31,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(32,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(32,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(33,'TOEIC04','TEACHER03');
insert into SUPERVISOR_RESPONSIBLE values(33,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(34,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(34,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(35,'TOEIC04','TEACHER04');
insert into SUPERVISOR_RESPONSIBLE values(35,'TOEIC04','SUPERVISOR03',null);
call AssignSessionForTeacher(36,'TOEIC04','TEACHER07');
insert into SUPERVISOR_RESPONSIBLE values(36,'TOEIC04','SUPERVISOR03',null);