USE ENGLISH_CENTER;

INSERT INTO SUPERVISOR_RESPONSIBLE VALUES
(1,'TOEIC03','SUPERVISOR01',NULL),
(2,'TOEIC03','SUPERVISOR01',NULL),
(3,'TOEIC03','SUPERVISOR01',NULL),
(1,'TOEIC04','SUPERVISOR01',NULL),
(2,'TOEIC04','SUPERVISOR01',NULL);

insert into SUPERVISOR_RESPONSIBLE values(21,'TOEIC03','SUPERVISOR01',NULL);

insert into SUPERVISOR_RESPONSIBLE values(5,'TOEIC03','SUPERVISOR03',NULL);